# 서버 포트 설정
server:
  port: 8080

# Logging(logback) 설정 파일 위치 지정
logging:
  config: classpath:logback-spring.xml


# application-api.yml, application-datasource.yml 을 include해서 사용하겠다는 설정
#spring:
#  profiles:
#    include:
#      - api
#      - datasource

# Key-Value Store(Couchbase) 설정
spring:
  couchbase:
    bootstrap-hosts: 211.104.171.162:8091
    bucket:
      name: admin
      password: passwd
  data:
    couchbase:
      auto-index: true
